name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Spec:
    if: ${{ github.event.pull_request.draft == false }} && ${{ github.repository_owner == 'puppetlabs' }}
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    secrets: "inherit"

  Acceptance:
    if: ${{ github.event.pull_request.draft == false }} && ${{ github.repository_owner == 'puppetlabs' }}
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main"
    with:
      flags: "--provision-service"
    secrets: "inherit"
