name: "ci"

on:
  pull_request_review_comment:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "tests"
        run: |
          echo github.event.comment.body
  Spec:
    if: |
      github.repository_owner == 'puppetlabs' ||
      contains(github.event.comment.body, '/ci run tests')
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    secrets: "inherit"

  Acceptance:
    if: |
      github.repository_owner == 'puppetlabs' ||
      contains(github.event.comment
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main"
    with:
      flags: "--provision-service"
    secrets: "inherit"
